// Presentation summaries only. Original observations and detailed Intelligence stay unchanged.
// Columns are English, German, French, Spanish and Italian; unknown language falls back to EN.
export const snapshotCompactCopy = {
  sunflower: ['June 2026 seed trade rose; unit value fell.', 'Saatguthandel stieg im Juni 2026; Einheitswert sank.', 'Échanges de semences en hausse en juin 2026 ; valeur unitaire en baisse.', 'Subieron los intercambios en junio de 2026; bajó el valor unitario.', 'Scambi di sementi in aumento a giugno 2026; valore unitario in calo.'],
  rye: ['Germany’s 2026 seed declarations show planned capacity.', 'Deutsche Saatgutmeldungen 2026 zeigen geplante Kapazität.', 'Les déclarations allemandes 2026 indiquent la capacité prévue.', 'Las declaraciones alemanas 2026 indican capacidad prevista.', 'Le dichiarazioni tedesche 2026 indicano capacità prevista.'],
  barley: ['Bavaria’s 2026 seed field results remain form-specific.', 'Bayerns Saatgut-Feldergebnisse 2026 bleiben nach Anbauform getrennt.', 'Résultats semenciers bavarois 2026 séparés par forme saisonnière.', 'Resultados semilleros bávaros 2026 separados por forma estacional.', 'Risultati sementieri bavaresi 2026 distinti per forma stagionale.'],
  'italian-ryegrass': ['Germany’s 2026 declarations show seed capacity.', 'Deutsche Meldungen 2026 zeigen Saatgutkapazität.', 'Les déclarations allemandes 2026 indiquent la capacité semencière.', 'Las declaraciones alemanas 2026 indican capacidad semillera.', 'Le dichiarazioni tedesche 2026 indicano capacità sementiera.'],
  'perennial-ryegrass': ['Latest trade unit value: February 2025.', 'Jüngster Handelswert je kg: Februar 2025.', 'Dernière valeur unitaire : février 2025.', 'Último valor unitario: febrero de 2025.', 'Ultimo valore unitario: febbraio 2025.'],
  'meadow-fescue': ['Germany reports seed capacity for 2026.', 'Deutschland meldet Saatgutkapazität für 2026.', 'L’Allemagne déclare une capacité semencière pour 2026.', 'Alemania declara capacidad semillera para 2026.', 'La Germania dichiara capacità sementiera per il 2026.'],
  'field-pea': ['June 2026 volume rose while trade unit value fell.', 'Junivolumen 2026 stieg; Handelswert je kg sank.', 'Volume en hausse en juin 2026 ; valeur unitaire en baisse.', 'Subió el volumen en junio de 2026; bajó el valor unitario.', 'Volume in aumento a giugno 2026; valore unitario in calo.'],
  'red-clover': ['Germany reports seed declarations for 2026.', 'Deutschland meldet Saatgutflächen für 2026.', 'L’Allemagne déclare des surfaces semencières pour 2026.', 'Alemania declara superficies semilleras para 2026.', 'La Germania dichiara superfici sementiere per il 2026.'],
  alfalfa: ['Latest trade unit value: December 2024.', 'Jüngster Handelswert je kg: Dezember 2024.', 'Dernière valeur unitaire : décembre 2024.', 'Último valor unitario: diciembre de 2024.', 'Ultimo valore unitario: dicembre 2024.'],
  soybean: ['June 2026 seed trade rose while unit value fell.', 'Saatguthandel stieg im Juni 2026; Einheitswert sank.', 'Échanges de semences en hausse en juin 2026 ; valeur unitaire en baisse.', 'Subieron los intercambios en junio de 2026; bajó el valor unitario.', 'Scambi di sementi in aumento a giugno 2026; valore unitario in calo.'],
  flax: ['2026 fibre-flax area grew in France, Belgium and the Netherlands.', 'Faserleinfläche 2026 stieg in Frankreich, Belgien und den Niederlanden.', 'Surfaces de lin fibre 2026 en hausse en France, Belgique et aux Pays-Bas.', 'Más superficie de lino textil en 2026 en Francia, Bélgica y Países Bajos.', 'Superficie di lino da fibra 2026 in crescita in Francia, Belgio e Paesi Bassi.'],
  'fodder-beet': ['German certification covers domestic and foreign-grown seed.', 'Deutsche Zertifizierung umfasst in- und ausländisches Saatgut.', 'Certification allemande : semences produites localement et à l’étranger.', 'La certificación alemana cubre semillas nacionales y extranjeras.', 'La certificazione tedesca comprende sementi nazionali ed estere.']
}
export function compactIntelligence(record, language='EN') {
  return snapshotCompactCopy[record.entity_id]?.[{EN:0,DE:1,FR:2,ES:3,IT:4}[language]??0] || record.market_situation
}
