"""Targeted, immutable-source audit. No extraction, allocation or implementation repair."""
import pathlib,json,csv,gzip,collections,hashlib,decimal,functools,argparse,datetime
D=decimal.Decimal
P=argparse.ArgumentParser();P.add_argument('--work',required=True);A=P.parse_args();W=pathlib.Path(A.work);R=pathlib.Path(__file__).resolve().parents[1];O=R/'docs/trade-pulse-40cn-audit-v1';O.mkdir(exist_ok=True);PERIOD='2026-06'
def load(p):return json.load(open(p))
def save(name,data):
 (O/(name+'.json')).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 if isinstance(data,list)and data:
  with (O/(name+'.csv')).open('w',newline='')as f:
   out=csv.DictWriter(f,fieldnames=list(data[0]));out.writeheader()
   for row in data:out.writerow({k:json.dumps(v,ensure_ascii=False,separators=(',',':'))if isinstance(v,(list,dict,bool))or v is None else v for k,v in row.items()})
entities=load(R/'docs/trade-cn-v1/TRADE_MARKET_ENTITIES.json');entity={x['cn8']:x for x in entities};official={x['cn8']:x for x in load(R/'data/trade-cn-v1/official-cn-extract.json')if x['year']==2026};species=load(R/'docs/trade-cn-v1/CN_AUDIT_121.json');master=load(R/'docs/crop-master-v1/CROP_MASTER_V1.json');byid={x['id']:x for x in master};categories=load(R/'docs/crop-master-v1/CATEGORY_TAXONOMY_V1.json');catnames={x['id']:x.get('name',x['id'])for x in categories};baseline=load(R/'data/multisource-trade-v1/trade_pulse_baseline.json');old={x['cn8']for x in baseline['scope']['included_cn_codes']};requests=load(W/'COMEXT_REQUEST_MANIFEST.json');assert len(requests)==1080 and all(x['status']=='RETRIEVED'for x in requests)
EU=set('AT BE BG HR CY CZ DE DK EE ES FI FR GR HU IE IT LT LU LV MT NL PL PT RO SE SI SK'.split());seen=set();seen4=set();duplicates4=0;totals=collections.defaultdict(lambda:[D(0),D(0),0]);latest_grains=collections.defaultdict(list);allrows=0;zero=0;flowcounts=collections.Counter();statuscounts=collections.Counter();updates=set()
@functools.lru_cache(maxsize=64)
def raw(file):return load(W/'raw-official/comext'/file)
for req in requests:assert hashlib.sha256((W/'raw-official/comext'/req['file']).read_bytes()).hexdigest()==req['sha256']
with gzip.open(W/'comext-normalized-public.jsonl.gz','rt')as f:
 for line in f:
  r=json.loads(line);allrows+=1;grain=(r['reporter'],r['partner'],r['period'],r['cn8'],r['reporting_flow']);assert grain not in seen;seen.add(grain)
  g4=grain[:4]
  if g4 in seen4:duplicates4+=1
  seen4.add(g4);assert r['classification']=='PUBLIC_SAFE'and r['cn8']in entity and r['reporter']in EU;assert r['reporter']!=r['partner'];assert '2024-01'<=r['period']<=PERIOD;datetime.datetime.strptime(r['period'],'%Y-%m');assert r['currency']=='EUR'and r['original_quantity_unit']=='100KG';assert r['species_allocation']=='NONE';assert r['representative_price']is None
  if r['view']=='eu_internal_trade':assert r['partner']in EU and r['reporting_flow']=='EXPORT'
  elif r['view']=='eu_imports':assert r['partner']not in EU and r['reporting_flow']=='IMPORT'
  elif r['view']=='eu_exports':assert r['partner']not in EU and r['reporting_flow']=='EXPORT'
  else:raise AssertionError('Unknown flow')
  data=raw(r['source_file']);dims={'freq':'M','reporter':r['reporter'],'partner':r['partner'],'product':r['cn8'],'flow':'1'if r['reporting_flow']=='IMPORT'else'2','time':r['period']}
  def cell(ind):
   dims['indicators']=ind;n=0
   for dim,size in zip(data['id'],data['size']):n=n*size+data['dimension'][dim]['category']['index'][dims[dim]]
   return data.get('value',{}).get(str(n))
  qty=cell('QUANTITY_IN_100KG');val=cell('VALUE_IN_EUROS');assert qty is not None and val is not None;kg=D(str(qty))*100;eur=D(str(val));assert abs(kg-D(str(r['net_weight_kg'])))<=D('0.000001')and eur==D(str(r['trade_value_eur']));assert kg>=0 and eur>=0;zero+=kg==0;flowcounts[r['view']]+=1;updates.add(r['source_updated'])
  for v in r['official_status'].values():
   if v:statuscounts[str(v)]+=1
  if r['period']==PERIOD:
   b=totals[(r['cn8'],r['view'])];b[0]+=kg;b[1]+=eur;b[2]+=1
   if r['view']=='eu_internal_trade':latest_grains[r['cn8']].append({'identity':r['id'],'reporter':r['reporter'],'partner':r['partner'],'kg':float(kg),'eur':float(eur),'source_file':r['source_file'],'source_url':r['source_url']})
kg=sum(totals[(c,'eu_internal_trade')][0]for c in entity);eur=sum(totals[(c,'eu_internal_trade')][1]for c in entity);oldkg=sum(totals[(c,'eu_internal_trade')][0]for c in old);oldeur=sum(totals[(c,'eu_internal_trade')][1]for c in old);newkg=kg-oldkg;neweur=eur-oldeur
pct=lambda n,d:round(float(n/d*100),6)if d else None
rows=[]
notes={'10019110':'Biological parent common-wheat mapping is valid as partial infraspecific scope, but the separate approved spelt commercial entity lacks its direct CN link. Re-link to existing spelt (Triticum aestivum subsp. spelta), without taxonomy expansion.','10019120':'Common wheat OR meslin is a combined customs scope. Never interpret its entire volume as Triticum aestivum alone; relabel GROUP_LEVEL and retain common-wheat only as scope candidate.','12091000':'Sugar-beet seed is a crop-type subset of Beta vulgaris. Whole sugar-beet trade must not automatically become vegetable-category trade merely through a beet/chard canonical label. Category allocation withheld pending explicit commercial-scope decision.','12092960':'Fodder-beet seed is a crop-type subset of Beta vulgaris. Whole fodder-beet trade must not automatically become vegetable-category trade. Category allocation withheld pending explicit commercial-scope decision.'}
for code,e in sorted(entity.items()):
 assert e['official_description']==official[code]['description'];assert 'for sowing' in e['official_description']and 'excl. for sowing'not in e['official_description']
 b=totals[(code,'eu_internal_trade')];gran='GROUP_LEVEL'if code=='10019120'else e['granularity'];specific=[{'id':s,'name':byid[s]['name'],'botanical':byid[s]['botanical']}for s in e['species_ids']]if gran=='SPECIES_SPECIFIC'else []
 sow='CONFIRMED_SOWING_SPECIFIC'if gran=='SPECIES_SPECIFIC'else'GROUP_LEVEL'if gran=='GROUP_LEVEL'else'PARTIAL'
 cats=e['seed_categories'];allocated=cats[0]if len(cats)==1 and code not in ['12091000','12092960']else None
 rows.append({'cn8':code,'official_cn_description':e['official_description'],'market_entity':e['id'],'linked_botanical_species_measured':specific,'linked_scope_candidates_only':[{'id':s,'botanical':byid[s]['botanical']}for s in e['species_ids']]if gran!='SPECIES_SPECIFIC'else[],'canonical_categories':cats,'allocated_category':allocated,'baseline_status':'OLD_BASELINE_CN'if code in old else'NEW_CN','sowing_specificity':sow,'sowing_use_confirmed':True,'original_granularity':e['granularity'],'audited_granularity':gran,'volume_kg':float(b[0]),'volume_tonnes':float(b[0]/1000),'trade_value_eur':float(b[1]),'observations':b[2],'total_volume_share_percent':pct(b[0],kg),'total_value_share_percent':pct(b[1],eur),'expansion_volume_share_percent':pct(b[0],newkg)if code not in old else None,'expansion_value_share_percent':pct(b[1],neweur)if code not in old else None,'source':'Eurostat COMEXT DS-045409;KSH official CN2026;official annual concordance','source_period':PERIOD,'flow':'EXPORTER_DISPATCH_INTRA_EU_ONLY','public_safe':True,'inclusion_recommendation':'INCLUDE_HEADLINE_SOWING_SCOPE;REPAIR_ATTRIBUTION_BEFORE_RELEASE'if code in notes else'INCLUDE_HEADLINE_SOWING_SCOPE','methodological_note':notes.get(code,'Group trade is not allocated to constituent species.'if gran=='GROUP_LEVEL'else'Partial botanical/crop-type scope is not full species coverage.'if gran=='PARTIAL'else'Sowing use and single botanical scope confirmed.'),'source_evidence':{'classification_url':official[code]['source_url'],'classification_sha256':official[code]['source_sha256'],'trade_request_pattern':'Preserved requests for all 27 reporters in COMEXT_REQUEST_MANIFEST.json'},'dominant_country_grain':max(latest_grains[code],key=lambda r:r['kg'])if latest_grains[code]else None})
for r in rows:
 r['concentration_flags']=[flag for key,flag in [('expansion_volume_share_percent','NEW_CODE_VOLUME_SHARE_AT_LEAST_25_PERCENT'),('expansion_value_share_percent','NEW_CODE_VALUE_SHARE_AT_LEAST_25_PERCENT')]if r[key]is not None and r[key]>=25]
new=[r for r in rows if r['baseline_status']=='NEW_CN'];save('CN_AUDIT_40',rows);save('NEW_CN_CONTRIBUTIONS_29',new)
rankv=sorted(new,key=lambda r:(-r['volume_kg'],r['cn8']));ranke=sorted(new,key=lambda r:(-r['trade_value_eur'],r['cn8']));save('TOP_10_CN_BY_VOLUME',rankv[:10]);save('TOP_10_CN_BY_VALUE',ranke[:10]);concentration={'denominator':'29-code expansion only; distinct from 40-code total shares','volume':{'top_1_cn':rankv[0]['cn8']},'value':{'top_1_cn':ranke[0]['cn8']}}
for n in [1,3,5,10]:concentration['volume']['top_'+str(n)+'_share_percent']=pct(sum(D(str(r['volume_kg']))for r in rankv[:n]),newkg);concentration['value']['top_'+str(n)+'_share_percent']=pct(sum(D(str(r['trade_value_eur']))for r in ranke[:n]),neweur)
concentration['flags']=['CONCENTRATED_NEW_CODE_VOLUME_TOP3_OVER_50_PERCENT'if concentration['volume']['top_3_share_percent']>50 else'NO_TOP3_VOLUME_DOMINANCE','CONCENTRATED_NEW_CODE_VALUE_TOP3_OVER_50_PERCENT'if concentration['value']['top_3_share_percent']>50 else'NO_TOP3_VALUE_DOMINANCE'];save('CONCENTRATION',concentration)
rec={'period':PERIOD,'flow':'INTRA_EU_DISPATCHES','old_11_kg_exact':str(oldkg),'new_29_kg_exact':str(newkg),'total_40_kg_exact':str(kg),'old_11_tonnes':float(oldkg/1000),'new_29_tonnes':float(newkg/1000),'total_40_tonnes':float(kg/1000),'old_11_eur_exact':str(oldeur),'new_29_eur_exact':str(neweur),'total_40_eur_exact':str(eur),'volume_reconciliation_residual_kg':float(oldkg+newkg-kg),'value_reconciliation_residual_eur':float(oldeur+neweur-eur),'arithmetic_tolerance':'Decimal exact arithmetic: zero residual. Two-decimal tonne display comparison <=0.005 tonne; independently rounded component displays may differ by <=0.01 tonne. EUR display tolerance <=0.005 EUR.','baseline_volume_display_match':round(float(oldkg/1000),2)==baseline['views']['eu_internal_trade']['latest']['volume_tonnes'],'baseline_value_exact_match':float(oldeur)==baseline['views']['eu_internal_trade']['latest']['trade_value_eur'],'expanded_volume_display_match':round(float(kg/1000),2)==251015.10,'expanded_value_exact_match':eur==D('400438328'),'all_history_observations':allrows,'duplicate_full_source_grain':0,'duplicate_reporter_partner_period_cn_without_flow':duplicates4,'four_dimension_duplicates_explanation':'Extra-EU import/export are distinct directional observations sharing reporter/partner/CN/month. FLOW is required in source identity; they are never combined into intra-EU dispatches.','quantity_unit':'SOURCE100KG x100=KG; x0.1=TONNES','value_unit':'EUR; no USD conversion','raw_cell_revalidation':'All accepted normalized rows checked against original JSONstat quantity/value cells','source_updates':sorted(updates),'zero_net_weight_rows':zero,'official_status_counts':dict(statuscounts),'all_history_flow_counts':dict(flowcounts)};assert all(rec[k]for k in ['baseline_volume_display_match','baseline_value_exact_match','expanded_volume_display_match','expanded_value_exact_match']);save('RECONCILIATION',rec)
cat=[]
for id,name in catnames.items():
 included=[r for r in rows if r['allocated_category']==id];ckg=sum(D(str(r['volume_kg']))for r in included);ceur=sum(D(str(r['trade_value_eur']))for r in included);linked=set(s for r in included for s in entity[r['cn8']]['species_ids']);cat.append({'category_id':id,'category_name':name,'volume_tonnes':float(ckg/1000)if included else None,'trade_value_eur':float(ceur)if included else None,'total_volume_share_percent':pct(ckg,kg)if included else None,'total_value_share_percent':pct(ceur,eur)if included else None,'cn_count':len(included),'cn_codes':[r['cn8']for r in included],'linked_canonical_entities':len(linked),'linked_true_seed_species':sum(byid[s]['kpi_eligible']for s in linked),'linked_species_are_contributors':False,'note':'Supported single-category customs totals only; excludes cross-category groups and unresolved beet crop types. Missing category coverage is absent, not zero.'})
unallocated=[r for r in rows if not r['allocated_category']];category={'categories':cat,'unallocated_cn_codes':[r['cn8']for r in unallocated],'unallocated_volume_tonnes':sum(r['volume_tonnes']for r in unallocated),'unallocated_value_eur':sum(r['trade_value_eur']for r in unallocated),'unallocated_volume_share_percent':pct(sum(D(str(r['volume_kg']))for r in unallocated),kg),'unallocated_value_share_percent':pct(sum(D(str(r['trade_value_eur']))for r in unallocated),eur),'largest_allocated_category_by_volume':max((x for x in cat if x['cn_count']),key=lambda x:x['volume_tonnes'])['category_id'],'largest_allocated_category_by_value':max((x for x in cat if x['cn_count']),key=lambda x:x['trade_value_eur'])['category_id'],'largest_category_caveat':'Largest among safely allocated categories; unallocated customs groups may dominate total value and are not a category.'};save('CATEGORY_ANALYSIS',category);save('CATEGORY_TABLE',cat)
# Conservative CURRENT activation coverage: keep faulty spelt link out and meslin group-level; no silent mapping activation.
coverage=[]
for s in species:
 id=s['canonical_species_id'];exact=[r['cn8']for r in rows if r['audited_granularity']=='SPECIES_SPECIFIC'and id in entity[r['cn8']]['species_ids']];partial=[r['cn8']for r in rows if r['audited_granularity']=='PARTIAL'and id in entity[r['cn8']]['species_ids']];groups=[r['cn8']for r in rows if r['audited_granularity']=='GROUP_LEVEL'and id in entity[r['cn8']]['species_ids']];pending=False;status='SPECIES_SPECIFIC'if exact else'PARTIAL_SPECIES_SCOPE'if partial else'GROUP_LEVEL_ONLY'if groups else'NO_COMPATIBLE_TRADE_DATA'
 coverage.append({'species_id':id,'name':s['common_name'],'botanical':s['botanical_name'],'coverage':status,'exact_cn_codes':exact,'partial_cn_codes':partial,'group_cn_scope_candidates':groups,'pending_existing_entity_relink':pending,'group_volume_allocated':False,'production_available_unchanged':s['production_available']})
counts=dict(collections.Counter(r['coverage']for r in coverage));save('SPECIES_COVERAGE',coverage);save('SPECIES_COVERAGE_SUMMARY',{'counts':counts,'denominator':121,'scope':'121 biological species only. Spelt is infraspecific evidence within Triticum aestivum and does not create a 122nd species; its separate commercial entity link remains pending. Partial scope never counts as full species coverage.'})
gate={'release_gate':'FAIL','headline_40_cn_numeric_and_sowing_scope':'PASS','core_extended_split_required':False,'reason':'No non-sowing code found and 40-code arithmetic is correct. Current release lacks a direct spelt commercial-entity link for CN10019110 despite a valid partial biological-parent mapping, under-labels mixed common-wheat/meslin CN10019120, and allocates sugar/fodder beet crop types to vegetable category without scope justification. Preserve totals but repair these attribution/label decisions before publication.','excluded_headline_cn_codes':[],'remove_codes':[],'relabel_or_relink_codes':['10019110','10019120'],'category_allocation_withheld_codes':['12091000','12092960'],'cross_category_unallocated_codes':['12092945','12092980','12099180'],'blocking_semantic_decisions':4,'implementation_repaired':False,'source_observations_changed':False,'source_aggregate_changed':False,'new_commit':'NONE','push':'NOT_PUSHED','deployment':'NONE','globalwits':'NOT_ACCESSED_FOR_NEW_RESEARCH;RAW_WORKBOOK_RETAINED_INTERNAL;0_VALUES_IN_PUBLIC_AGGREGATE'};save('RELEASE_GATE',gate)
qa={'numeric_source_qa':'PASS','semantic_release_blockers':4,'raw_cell_checks':allrows,'source_hash_checks':len(requests),'duplicates_including_flow':0,'duplicate_four_dimension_keys_with_distinct_flow':duplicates4,'public_safe':'PASS','no_species_allocation':'PASS','no_provider_merge':'PASS','no_interpolation':'PASS','commodity_non_sowing_codes':0,'category_partition':'PASS_WITH_EXPLICIT_UNALLOCATED_BUCKET','observations_unchanged':allrows==153838};assert sum(D(str(r['volume_tonnes']))for r in cat if r['volume_tonnes']is not None)+sum(D(str(r['volume_tonnes']))for r in unallocated)==kg/1000;save('AUDIT_QA',qa)
summary={'cn_codes_total':40,'old_cn_codes':11,'new_cn_codes':29,'old_11_volume':round(float(oldkg/1000),2),'new_29_volume':round(float(newkg/1000),2),'total_40_volume':round(float(kg/1000),2),'old_11_value':float(oldeur),'new_29_value':float(neweur),'total_40_value':float(eur),'species_specific_cn':sum(r['audited_granularity']=='SPECIES_SPECIFIC'for r in rows),'group_level_cn':sum(r['audited_granularity']=='GROUP_LEVEL'for r in rows),'partial_cn':sum(r['audited_granularity']=='PARTIAL'for r in rows),'ambiguous_sowing_cn':0,'excluded_cn':0,'coverage':counts,'concentration':concentration,'category':{k:v for k,v in category.items()if k!='categories'},'release_gate':'FAIL'};save('SUMMARY',summary);print(json.dumps(summary,indent=2))
