"""Reproducible public CN audit and bounded COMEXT linkage; immutable baseline preserved."""
import csv,hashlib,json,pathlib,itertools,collections
R=pathlib.Path(__file__).resolve().parents[1];O=R/'docs/trade-cn-v1';I=R/'data/trade-cn-v1';O.mkdir(exist_ok=True)
def read(p):return json.loads((R/p).read_text())
def dump(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def tab(n,rows):
 dump(O/(n+'.json'),rows)
 if rows:
  with (O/(n+'.csv')).open('w',newline='') as f:
   w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n');w.writeheader()
   for r in rows:w.writerow({k:json.dumps(v,ensure_ascii=False) if isinstance(v,(dict,list,bool)) or v is None else v for k,v in r.items()})
cn=read('data/trade-cn-v1/official-cn-extract.json');official={r['cn8']:r for r in cn if r['year']==2026};previous={r['cn8']:r for r in cn if r['year']==2025};dec=read('data/trade-cn-v1/decisions.json');cov=read('docs/species-coverage-v1/SPECIES_COVERAGE_121.json');master=read('docs/crop-master-v1/CROP_MASTER_V1.json');byid={e['id']:e for e in master};market=read('src/generated/market_public.json');pulse=read('src/generated/trade_pulse_public.json')
def sowing(c):
 t=official.get(c,{}).get('description','').lower()
 return 'for sowing' in t and 'excl. for sowing' not in t and 'excl. seed for sowing' not in t
# Official-only extraction is committed separately; source payloads remain in checkpoint.
new=read('data/trade-cn-v1/comext-normalized.json') if (I/'comext-normalized.json').exists() else []
new_by=collections.defaultdict(list)
for r in new:new_by[r['cn8']].append(r)
existing={x['cn8']:x for x in market['crops']};audit=[];entities={};links=[]
for row in cov:
 sid=row['canonical_species_id'];codes=list(row['cn_codes']);status=row['cn_status'];reason='Existing mapping audited against official 2026 denomination; original scope retained.'
 if sid in dec['vegetable_group']:codes=['12099180'];status='GROUP_LEVEL';reason=dec['vegetable_reason']
 if sid in dec['explicit']:d=dec['explicit'][sid];codes=d['codes'];status=d['status'];reason=d['reason']
 if sid in dec['retain_review']:codes=[];status='REVIEW_REQUIRED';reason=dec['review_reason']
 if sid in dec['non_sowing_evidence']:codes=list(set(codes+dec['non_sowing_evidence'][sid]))
 original=list(codes);usable=[c for c in codes if sowing(c)];excluded=[c for c in codes if not sowing(c)]
 # Existing commodity-only PARTIAL codes do not constitute sowing trade coverage.
 if excluded and not usable:status='NOT_AVAILABLE';reason='Official denomination does not isolate sowing use. Commodity codes retained in audit only; never activated.'
 if not codes and status=='PARTIAL':status='NOT_AVAILABLE';reason='No verified sowing-specific code in recovered master. Original relationship retained in provenance only.'
 codes=usable
 known_descriptions=[official[c] for c in codes]
 classifications=sorted({c[:4] for c in codes});specific=status=='CONFIRMED'
 direct_base=bool(row['trade_evidence']);new_direct=sid in ['soybean','maize'] and any(new_by[c] for c in codes)
 for c in codes:
  if c not in entities:
   ebase=existing.get(c);rows=new_by[c];periods=sorted({r['period'] for r in rows});has=bool(ebase or rows)
   entities[c]=dict(id='CN-'+c,cn8=c,cn6=c[:6],cn4=c[:4],hs6=c[:6],official_description=official[c]['description'],nomenclature_year=2026,granularity='SPECIES_SPECIFIC' if specific else 'GROUP_LEVEL' if status=='GROUP_LEVEL' else 'PARTIAL',species_ids=[],botanical_names=[],seed_categories=[],sowing_status='SOWING_SPECIFIC',contains_non_seed_material=False,classification='PUBLIC_SAFE',confidence='HIGH_FOR_CUSTOMS_SCOPE',trade_available=has,existing_market_slug=ebase['slug'] if ebase else None,source_reference='KSH_CN_2026',historical_2025_definition_unchanged=previous.get(c,{}).get('description')==official[c]['description'],earliest_usable_period=ebase['history'][0]['period'] if ebase else min(periods,default=None),latest_usable_period=ebase['latest_completed_period'] if ebase else max(periods,default=None),trade_scope='Existing verified COMEXT market series' if ebase else 'DE→PL, FR→PL, NL→PL, PL→DE dispatches only; not country totals or an EU total',limitations=['No allocation to constituent species. No mirror-flow summation.','2024 concordance was not newly verified; existing 2024 series retain baseline provenance.','Mapping confidence is not market attractiveness.'],periods=[])
  entities[c]['seed_categories']=sorted(set(entities[c]['seed_categories']+[row['seedtrade_category']]))
  entities[c]['species_ids'].append(sid);entities[c]['botanical_names'].append(row['botanical_name']);links.append(dict(canonical_species_id=sid,botanical_name=row['botanical_name'],cn8=c,trade_market_entity_id='CN-'+c,mapping_status=status,scope_rationale=reason,public_safe=True))
 hist={c:dict(confirmed_2025=c in previous,description_unchanged=previous.get(c,{}).get('description')==official[c]['description'],confirmed_2024=False) for c in codes}
 available_codes=[c for c in codes if existing.get(c) or new_by[c]]
 periods=[r['period'] for c in codes for r in new_by[c]]
 audit.append(dict(canonical_species_id=sid,common_name=row['common_name'],botanical_name=row['botanical_name'],biological_species_key=row['biological_species_key'],seed_category=row['seedtrade_category'],use_tags=row['use_tags'],current_cn_status=row['cn_status'],proposed_cn_status=status,cn4=classifications,cn6=sorted({c[:6] for c in codes}),cn8=codes,hs6=sorted({c[:6] for c in codes}),sowing_status='SOWING_SPECIFIC' if codes else 'NOT_SOWING_SPECIFIC' if excluded else 'REVIEW_REQUIRED' if status=='REVIEW_REQUIRED' else 'NOT_AVAILABLE',sowing_specific_codes=codes,excluded_commodity_or_unsuitable_codes=excluded,original_cn_codes=row['cn_codes'],original_cn_provenance=row['cn_provenance'],cn_descriptions=known_descriptions,species_specific_code=specific,contains_multiple_species=status=='GROUP_LEVEL',contains_non_seed_material=False if codes else None,comext_compatible=bool(codes),cn_history=hist,earliest_usable_trade_period=min(periods,default='2024-01' if direct_base else None),latest_usable_trade_period=max(periods,default=row['latest_trade_period']),species_level_trade=direct_base or new_direct,full_species_specific_trade=direct_base or sid=='soybean' and new_direct,group_or_partial_trade=bool(available_codes) and not (direct_base or new_direct),trade_available_codes=available_codes,production_available=row['any_production_metric'],public_safe=True,decision_rationale=reason,confidence='HIGH_FOR_BOUNDED_CUSTOMS_SCOPE' if codes else 'LIMITED_OR_REVIEW',limitations=['Customs mapping is not evidence that the species contributed any amount to a group.','No interpolation, proportional allocation, species shares or supply signal.','Taxonomy and production datasets remain unchanged.'],taxonomy_provenance=row['identity_provenance']))
# One unique customs entity per leaf code; mixing mappings never creates duplicate volume.
for c,e in entities.items():
 if len(e['species_ids'])>1:e['granularity']='GROUP_LEVEL'
 for country in sorted({r['reporter'] for r in new_by[c]}):
  e['periods'].extend(dict(country=country,destination=r['partner'],period=r['period'],volume_kg=r['net_weight_kg'],trade_value_eur=r['trade_value_eur'],representative_price_eur_kg=None,price_status='WITHHELD_NOT_RUN_THROUGH_EXISTING_REPRESENTATIVE_PRICE_ENGINE',source='Eurostat COMEXT DS-045409',source_observation_id=r['id']) for r in new_by[c] if r['reporter']==country)
intersection=[dict(canonical_species_id=r['canonical_species_id'],botanical_name=r['botanical_name'],production=r['production_available'],species_level_trade=r['species_level_trade'],useful_customs_group_available=r['group_or_partial_trade'],state='PRODUCTION_AND_TRADE' if r['production_available'] and r['species_level_trade'] else 'PRODUCTION_ONLY' if r['production_available'] else 'TRADE_ONLY' if r['species_level_trade'] else 'NEITHER',commercial_interpretation_candidate=r['production_available'] and r['species_level_trade'],interpretation='NOT_PERFORMED') for r in audit]
counts=collections.Counter(r['proposed_cn_status'] for r in audit);sow=collections.Counter(r['sowing_status'] for r in audit);states=collections.Counter(r['state'] for r in intersection)
summary=dict(STARTING_HEAD='9e52d03c7a761fcbc0d802451c95a147d0583bca',DISTINCT_SEED_SPECIES=len(audit),CANONICAL_MARKET_ENTITIES=136,SEED_CATEGORIES=10,CATCH_CROP_SPECIES=52,SPECIES_WITH_TRADE_DATA_BEFORE=9,SPECIES_WITH_TRADE_DATA_AFTER=sum(r['species_level_trade'] for r in audit),FULL_SPECIES_SPECIFIC_TRADE=sum(r['full_species_specific_trade'] for r in audit),SPECIES_LEVEL_TRADE_COVERAGE_PERCENT=round(sum(r['species_level_trade'] for r in audit)/121*100,2),TRADE_MARKET_ENTITIES=len(entities),TRADE_MARKET_ENTITIES_WITH_DATA=sum(e['trade_available'] for e in entities.values()),USEFUL_TRADE_MARKET_COVERAGE=sum(bool(r['trade_available_codes']) for r in audit),USEFUL_COVERAGE_SCOPE='Species linked to an observed customs entity; not confirmed species-level trade',CN_STATUS_COUNTS=dict(counts),SOWING_STATUS_COUNTS=dict(sow),SPECIES_WITH_PRODUCTION_DATA=82,INTERSECTION=dict(states),NEW_CN_MAPPINGS=sum(len(set(r['cn8'])-set(r['original_cn_codes'])) for r in audit),SPECIES_GAINING_NEW_CN_LINKS=sum(bool(set(r['cn8'])-set(r['original_cn_codes'])) for r in audit),SPECIES_WITH_CHANGED_CN_CODE_SETS=sum(set(r['cn8'])!=set(r['original_cn_codes']) for r in audit),NEW_COMEXT_OBSERVATIONS=len(new),BASELINE_COMPLETED_TRADE_PULSE_OBSERVATIONS=pulse['accepted_observations'],COMPLETED_TRADE_PULSE_PLUS_NEW=pulse['accepted_observations']+len(new),BASELINE_TRADE_OBSERVATIONS=read('src/generated/public_data_manifest.json')['datasets']['comext']['public_safe_observations'],TOTAL_TRADE_OBSERVATIONS=read('src/generated/public_data_manifest.json')['datasets']['comext']['public_safe_observations']+len(new),OBSERVATION_COUNT_SCOPE='Baseline manifest-reported 56,741 public-safe rows (not recounted from raw) plus 502 newly recounted bilateral rows on disjoint CN codes. Completed Trade Pulse subset remains separately reported; no volume sum across entities',PUBLIC_SAFE='PASS',PROVENANCE='PASS',COMMODITY_CONTAMINATION='NONE',REPRESENTATIVE_PRICE_QA='EXISTING_ENGINE_PRESERVED;NEW_PRICES_WITHHELD')
tab('CN_AUDIT_121',audit);tab('TRADE_MARKET_ENTITIES',list(entities.values()));tab('SPECIES_CN_TRADE_MAP',links);tab('TRADE_COVERAGE',[{k:r[k] for k in ['canonical_species_id','botanical_name','species_level_trade','group_or_partial_trade','trade_available_codes','earliest_usable_trade_period','latest_usable_trade_period']} for r in audit]);tab('PRODUCTION_TRADE_INTERSECTION',intersection);tab('UNRESOLVED_MAPPINGS',[r for r in audit if r['proposed_cn_status'] in ['REVIEW_REQUIRED','NOT_AVAILABLE']]);tab('CN_EVIDENCE_REGISTER',cn)
dump(R/'src/generated/trade_entity_scope.json',{c:dict(granularity=e['granularity'],species_ids=e['species_ids']) for c,e in entities.items() if c in existing})
dump(O/'SUMMARY.json',summary);dump(O/'COMEXT_COVERAGE_REPORT.json',dict(summary=summary,scope='Targeted DE→PL FR→PL NL→PL PL→DE exporter dispatches, January 2025–June 2026, ten previously unexposed CN leaf codes. No national/aggregate overlap with baseline codes; no species allocation.',existing_baseline_preserved=True,earlier_2024_download='KSH 2024 structure URL returned 404; no historical concordance invented.',invalid_partner_query='EU27_2020 partner filter returned empty dimensions, never normalized; replaced with verified bilateral country partners.',bulk_request='413 Request Entity Too Large; reduced to standard filtered individual requests.',missing_values='Absent, never zero-filled',representative_price='New prices withheld; existing validated calculations unchanged'))
dump(R/'src/generated/trade_cn_public.json',dict(version='TRADE_CN_COVERAGE_V1',classification='PUBLIC_SAFE',summary=summary,entities=[{k:v for k,v in e.items() if k not in ['historical_2025_definition_unchanged']} for e in entities.values()]))
dump(R/'public/data/trade-cn-coverage-v1.json',dict(summary=summary,species=audit,entities=list(entities.values()),links=links))
print(json.dumps(summary))
