"""Audit held evidence; restore only original price points exactly witnessed by official rows."""
import calendar,collections,csv,gzip,hashlib,json
from decimal import Decimal
from pathlib import Path
R=Path(__file__).resolve().parents[1];D=R/'docs/price-kpi-audit-v1';D.mkdir(exist_ok=True)
load=lambda p:json.loads(p.read_text())
data=load(R/'src/generated/market_catalogue_public.json');legacy=load(R/'src/generated/market_public.json');pulse=load(R/'src/generated/trade_pulse_public.json');cn={c['cn8']:c for c in load(R/'src/generated/trade_cn_public.json')['entities']}
source=R/'docs/market-commercial-v4/evidence/comext-normalized-public.jsonl.gz';digest=hashlib.sha256(source.read_bytes()).hexdigest();assert digest==pulse['source_artifact_sha256']
with gzip.open(source,'rt') as f:rows=[json.loads(l) for l in f]
assert len({r['id'] for r in rows})==len(rows)
exports=collections.defaultdict(list)
for r in rows:
 if r['reporting_flow']=='EXPORT':exports[(r['cn8'],r['period'])].append(r)
ids=[x['entity'] for x in load(R/'docs/market-commercial-v4/PRICE_EVIDENCE_AUDIT.json')];assert len(ids)==8
witnesses=[];audits=[]
for entity in ids:
 c=next(c for c in data['cards'] if c['market_entity_id']==entity)
 old=next(o for o in legacy['crops'] if o['species_id']==c['biological_species_id'] and o['cn8'] in c['CN_codes'])
 code=str(old['cn8']);definition=cn[code];points=[];rejected=[]
 form=c['commercial_entity_type']=='COMMERCIAL_FORM'
 direct=len(definition['species_ids'])==1 and definition['species_ids'][0]==c['biological_species_id'] and definition['sowing_status']=='SOWING_SPECIFIC' and not form
 for p in old['history']:
  subset=exports[(code,p['period'])];kg=sum((Decimal(str(r['net_weight_kg'])) for r in subset),Decimal(0));value=sum((Decimal(str(r['trade_value_eur'])) for r in subset),Decimal(0))
  match=bool(kg and kg==Decimal(str(p['volume_kg'])) and abs(value/kg-Decimal(str(p['price_eur_kg'])))<Decimal('1e-9'))
  if direct and match:
   identifier='PRICE-WITNESS:'+entity+':'+p['period'];scope='EU-27 seed exports to EU and third-country destinations; representative customs-derived export unit value.'
   if entity=='italian-ryegrass':scope+=' Lolium multiflorum includes Westerwolds; not a form-specific price.'
   point={'period':p['period'],'price_eur_kg':float(p['price_eur_kg']),'original_price_eur_kg':p['price_eur_kg'],'yoy_percent':None,'classification':'PUBLIC_SAFE','eligible':True,'scope_verified':True,'species_attribution_verified':True,'unit':'EUR_PER_KG','methodology':'Existing published representative unit value; exact reconstruction: sum(EUR export values)/sum(net_weight_kg) across EU27 exporter reports, intra and extra EU, country partners only; no mirrored imports. Not a transaction price.','scope':scope,'source':'Eurostat COMEXT DS-045409; existing SeedTrade representative unit-value series','source_url':'https://ec.europa.eu/eurostat/web/international-trade-in-goods/database','source_sha256':digest,'source_dataset':'src/generated/market_public.json + preserved complete COMEXT universe','source_witness_id':identifier,'retrieval_date':sorted({r['retrieval_date'] for r in subset})[-1],'cn_codes':[code],'quantity_basis_kg':float(kg),'value_basis_eur':float(value)}
   points.append(point);witnesses.append({'id':identifier,'entity':entity,'period':p['period'],'cn8':code,'quantity_basis_kg':str(kg),'value_basis_eur':str(value),'source_observation_ids':[r['id'] for r in subset],'source_file_sha256':{r['source_file']:r['source_sha256'] for r in subset}})
  else:rejected.append({'period':p['period'],'reason':'PARENT_SPECIES_PRICE_NOT_ALLOCATABLE_TO_COMMERCIAL_FORM' if form else 'LEGACY_POINT_NOT_EXACTLY_RECONCILED_TO_HELD_SOURCE_VINTAGE','legacy_quantity_kg':p['volume_kg'],'current_source_quantity_kg':str(kg),'legacy_price':p['price_eur_kg'],'current_source_value_eur':str(value)})
 points.sort(key=lambda p:p['period']);lookup={p['period']:p for p in points}
 for p in points:
  prior=lookup.get(str(int(p['period'][:4])-1)+p['period'][4:])
  if prior and prior['price_eur_kg']>0:p['yoy_percent']=(p['price_eur_kg']/prior['price_eur_kg']-1)*100
 c['price_observations']=points;c['price_history']=points;c['price_period']=points[-1]['period'] if points else None;c['price_scope']=points[-1]['scope'] if points else None;c['representative_price_eur_kg']=points[-1]['price_eur_kg'] if points else None;c['representative_price_yoy']=points[-1]['yoy_percent'] if points else None
 c['price_scope_status']='INDEPENDENT_SCOPE_SOURCE_VALUES_EXACTLY_RECONCILED' if points else 'PARENT_SPECIES_PRICE_NOT_ALLOCATABLE_TO_COMMERCIAL_FORM' if form else 'REVIEW_REQUIRED'
 final='PUBLISHABLE' if points else 'NOT PUBLISHABLE' if form else 'REVIEW REQUIRED'
 audits.append({'commercial_entity':entity,'common_name':c['common_name_en'],'botanical_name':c['botanical_display_name'],'biological_species':c['accepted_taxon'],'displayed_legacy_price':old['price_eur_kg'],'unit':'EUR_PER_KG','legacy_observation_period':old['latest_completed_period'],'source_dataset':'src/generated/market_public.json','cn_codes':[code],'official_cn_description':definition['official_description'],'sowing_status':definition['sowing_status'],'species_scope':definition['botanical_names'],'scope_precision':'PARENT_SPECIES_NOT_FORM_SPECIFIC' if form else 'DIRECT_BIOLOGICAL_SPECIES_INCLUDING_FORMS' if entity=='italian-ryegrass' else 'DIRECT_BIOLOGICAL_SPECIES','quantity_basis':'EU27 reporter export/dispatch net weight kg; EU and third-country partners; no mirror imports','value_basis':'EUR declared statistical export value for exactly the same observations','calculation_formula':'sum(trade_value_eur)/sum(net_weight_kg)','legacy_implied_value_eur':str(Decimal(old['price_eur_kg'])*Decimal(old['volume_kg'])),'legacy_quantity_basis_kg':old['volume_kg'],'provenance':'Exact original published price and quantity matched to retained official observations; annual CN scope compatibility retained','public_safe_status':'PUBLIC_SAFE' if points else 'SOURCE_PUBLIC_SAFE;PRICE_ATTRIBUTION_NOT_PUBLISHABLE','v4_rejection':'Independent price geography/methodology not established','v4_rejection_required':False if points else True,'decision':final,'latest_publishable_period':c['price_period'],'latest_publishable_price':c['representative_price_eur_kg'],'verified_price_points':len(points),'verified_source_witness_ids':[p['source_witness_id'] for p in points],'unresolved_original_source_observations':'Original earlier source vintage unavailable for non-reconciling legacy points; no silent correction','rejected_points':rejected,'decision_rationale':'Use latest independently reproduced existing point; no equality with trade-volume month required.' if points else 'Parent Lolium multiflorum price cannot be assigned to Westerwold commercial form.'})
period=pulse['views']['eu_internal_trade']['latest']['period'];codes={x['cn8'] for x in pulse['scope']['included_cn_codes']};subset=[r for r in rows if r['period']==period and r['view']=='eu_internal_trade' and r['cn8'] in codes];EU=set('AT BE BG HR CY CZ DE DK EE ES FI FR GR HU IE IT LT LU LV MT NL PL PT RO SE SI SK'.split())
keys=[(r['reporter'],r['partner'],r['reporting_flow'],r['cn8'],r['period']) for r in subset];kg=sum((Decimal(str(r['net_weight_kg'])) for r in subset),Decimal(0));eur=sum((Decimal(str(r['trade_value_eur'])) for r in subset),Decimal(0));tonnes=kg/1000
assert abs(tonnes-Decimal(str(pulse['views']['eu_internal_trade']['latest']['volume_tonnes'])))<=Decimal('0.005');assert len(subset)==pulse['views']['eu_internal_trade']['latest']['observation_count'];assert len(keys)==len(set(keys));assert all(r['reporter'] in EU and r['partner'] in EU and r['reporter']!=r['partner'] and r['reporting_flow']=='EXPORT' for r in subset)
audit={'raw_tonnes':str(tonnes),'display':'251.0k t','period_type':'SINGLE_LATEST_COMPLETED_MONTH','start':period+'-01','end':period+'-'+str(calendar.monthrange(*map(int,period.split('-')))[1]),'period':period,'formula':'SUM(net_weight_kg)/1000; included 40 sowing CN8; period=canonical completed month; EU27 exporter-reported intra-EU dispatches only','codes':sorted(codes),'cn_count':len(codes),'observation_count':len(subset),'quantity_basis_kg':str(kg),'value_basis_eur':str(eur),'scope':'EU27 reporter to EU27 partner; export/dispatch only; country partners; no self-flows','source_sha256':digest,'ui_trace':['EuMarketSummary: market_catalogue_public.eu_summary.trade_volume_t','generate_market_catalogue: trade_pulse_public.views.eu_internal_trade.latest.volume_tonnes','scripts/multisource/recalculate.py: M[(view,period)] from unique official normalized observations'],'catalogue_card_summation':False,'canonical_tonnes':str(pulse['views']['eu_internal_trade']['latest']['volume_tonnes']),'rounding_difference_tonnes':str(tonnes-Decimal(str(pulse['views']['eu_internal_trade']['latest']['volume_tonnes']))),'rounding_tolerance_tonnes':'0.005;canonical headline rounds source sum to 2 decimals','source_observation_ids':[r['id'] for r in subset],'double_counting_audit':'PASS','double_counting_method':'Unique reporter-partner-export-CN8-month grain; no intra-EU mirror imports; no entity/category/species join in SUM; one code included once; each source id unique; group CN scopes counted once as customs scopes, never allocated to species.'}
assert eur==Decimal(str(pulse['views']['eu_internal_trade']['latest']['trade_value_eur']))
(D/'PRICE_CANDIDATE_AUDIT.json').write_text(json.dumps(audits,ensure_ascii=False,indent=2)+'\n');(D/'PRICE_OBSERVATION_WITNESSES.json').write_text(json.dumps(witnesses,ensure_ascii=False,separators=(',',':'))+'\n');(D/'GLOBAL_KPI_AUDIT.json').write_text(json.dumps(audit,indent=2)+'\n');(D/'DOUBLE_COUNTING_AUDIT.json').write_text(json.dumps({k:v for k,v in audit.items() if k in ['double_counting_audit','double_counting_method','source_sha256','observation_count','codes','catalogue_card_summation']},indent=2)+'\n')
with (D/'PRICE_CANDIDATE_AUDIT.csv').open('w',newline='') as f:
 fields=[k for k in audits[0] if k!='rejected_points'];w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows({k:json.dumps(v,ensure_ascii=False) if isinstance(v,(list,dict)) else v for k,v in a.items() if k in fields} for a in audits)
(R/'src/generated/market_catalogue_public.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':'))+'\n')
fields=['market_entity_id','slug','common_name_en','botanical_display_name','use_tags','public_safe_status','trade_volume_t','trade_volume_yoy','latest_trade_period','CN_status','trade_history','price_observations']
snapshot=[{k:c[k] for k in fields} for c in data['cards'] if c['trade_volume_t'] is not None or c['price_observations']]
(R/'src/generated/market_snapshot_public.json').write_text(json.dumps({'source':'CANONICAL_CATALOGUE','cards':snapshot,'categories':[{'id':c['id'],'title':c['title']} for c in data['categories']]},ensure_ascii=False,separators=(',',':'))+'\n')
print(json.dumps({'candidate_decisions':collections.Counter(a['decision'] for a in audits),'price_cards':sum(bool(c['price_observations']) for c in data['cards']),'snapshot':len(snapshot),'period':period,'tonnes':str(tonnes),'observations':len(subset)}))
