"""Methodology-only resolution from recovered audit; no requests or UI mutation."""
import pathlib,json,csv,hashlib,decimal,collections
R=pathlib.Path(__file__).resolve().parents[1]
I=R/'docs/trade-pulse-40cn-audit-v1'
O=R/'docs/trade-pulse-40cn-fail-resolution-v1'
O.mkdir(exist_ok=True)
D=decimal.Decimal
def load(p):return json.loads(p.read_text())
def save(n,data):
 if isinstance(data,list) and data:
  keys=list(dict.fromkeys(k for x in data for k in x))
  data=[{k:x.get(k)for k in keys}for x in data]
 (O/(n+'.json')).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 if isinstance(data,list) and data:
  with (O/(n+'.csv')).open('w',newline='') as f:
   w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader()
   for x in data:w.writerow({k:json.dumps(v,ensure_ascii=False,separators=(',',':')) if isinstance(v,(dict,list,bool)) or v is None else v for k,v in x.items()})
rows=load(I/'CN_AUDIT_40.json');original_gate=load(I/'RELEASE_GATE.json')
master=load(R/'docs/crop-master-v1/CROP_MASTER_V1.json');byid={x['id']:x for x in master}
recovered=load(I/'RECONCILIATION.json');sourceqa=load(I/'AUDIT_QA.json')
decisions=[
 {'cn8':'10019110','previous_fail_reason':'Missing direct separate commercial Spelt link; partial biological-parent mapping is valid.','resolution':'Direct CN-to-existing-commercial-entity link to spelt; retain biological parent common-wheat as PARTIAL_SCOPE. No new species or entity.','commercial_entity_id':'spelt','botanical':'Triticum aestivum subsp. spelta','biological_species':'Triticum aestivum','status':'RESOLVED_MODEL_ONLY'},
 {'cn8':'10019120','previous_fail_reason':'Common wheat or meslin presented as partial common-wheat scope.','resolution':'GROUP_LEVEL customs entity CN-10019120. Common-wheat is a scope candidate only; no whole-CN common-wheat volume and no constituent allocation.','commercial_entity_id':'CN-10019120','botanical':None,'status':'RESOLVED_MODEL_ONLY'},
 {'cn8':'12091000','previous_fail_reason':'Sugar-beet crop type inherited vegetable category from Beta vulgaris biological link.','resolution':'Keep sugar-beet customs crop-type evidence at CN-12091000 with Beta vulgaris PARTIAL_SCOPE; category UNALLOCATED_COMMERCIAL_SCOPE. Do not invent an eleventh category or pretend vegetable usage.','commercial_entity_id':'CN-12091000','botanical':'Beta vulgaris','status':'RESOLVED_BY_WITHHOLDING_CATEGORY'},
 {'cn8':'12092960','previous_fail_reason':'Fodder-beet crop type inherited vegetable category from Beta vulgaris biological link.','resolution':'Keep fodder-beet customs crop-type evidence at CN-12092960 with Beta vulgaris PARTIAL_SCOPE; category UNALLOCATED_COMMERCIAL_SCOPE. Original botanical terminology retained; no forced vegetable allocation.','commercial_entity_id':'CN-12092960','botanical':'Beta vulgaris','source_botanical':'Beta vulgaris var. alba','status':'RESOLVED_BY_WITHHOLDING_CATEGORY'}]
decision={x['cn8']:x for x in decisions};save('FAIL_REASON_RESOLUTIONS',decisions)
out=[]
for x in rows:
 assert x['sowing_use_confirmed'] and x['public_safe'] and 'for sowing' in x['official_cn_description']
 y=dict(x);g=x['audited_granularity'];code=x['cn8']
 y.update(classification='CORE_SEED_TRADE',classification_reason='Explicit seed-for-sowing customs scope is safe in a CN-defined headline. Botanical precision is a separate dimension and is disclosed; no species completeness claim.',sowing_specificity='CONFIRMED_SOWING_SPECIFIC',botanical_precision=g,precision='SPECIES_SPECIFIC' if g=='SPECIES_SPECIFIC' else 'MARKET_ENTITY_SPECIFIC' if code=='10019110' else 'GROUP_LEVEL' if g=='GROUP_LEVEL' else 'MARKET_ENTITY_SPECIFIC',measurement_entity_id='spelt' if code=='10019110' else x['market_entity'],direct_commercial_entity_ids=['spelt'] if code=='10019110' else [v['id'] for v in x['linked_botanical_species_measured']],category_status='ALLOCATED_CN_CATEGORY' if x['allocated_category'] else 'UNALLOCATED_COMMERCIAL_SCOPE',species_volume_allocation='NONE_FOR_GROUPS',public_safe=True,provenance={'original_audit':'CN_AUDIT_40.json','original_audit_version':'r2','classification_evidence':x['source_evidence'],'period':x['source_period'],'source':x['source']},implementation_status='RECOMMENDATION_ONLY_NOT_APPLIED')
 if code in decision:y['resolved_fail_reason']=decision[code]
 if code=='10019110':y['commercial_botanical']='Triticum aestivum subsp. spelta';y['biological_parent']='Triticum aestivum';y['partial_parent_scope_only']=True
 if not y['allocated_category']:y['category_reason']='Cross-category customs group or commercial beet crop type does not safely resolve to one approved primary category. Keep in headline and explicit unallocated category reconciliation bucket.'
 out.append(y)
save('CN_CLASSIFICATION_40',out)
classes=['CORE_SEED_TRADE','EXTENDED_SEED_TRADE','REVIEW_REQUIRED','EXCLUDE']
total_kg=sum(D(str(x['volume_kg'])) for x in out);total_eur=sum(D(str(x['trade_value_eur'])) for x in out)
aggregates=[]
for c in classes:
 rr=[x for x in out if x['classification']==c];kg=sum((D(str(x['volume_kg']))for x in rr),D(0));eur=sum((D(str(x['trade_value_eur']))for x in rr),D(0))
 aggregates.append({'classification':c,'cn_count':len(rr),'cn_codes':[x['cn8']for x in rr],'volume_kg_exact':str(kg),'volume_tonnes_exact':str(kg/1000),'volume_tonnes_display':str((kg/1000).quantize(D('.01'))),'value_eur_exact':str(eur),'empty_universe_not_missing_data':not rr})
save('SAFE_AGGREGATES',aggregates)
assert total_kg==D('251015101') and total_eur==D('400438328')
assert sum(D(x['volume_kg_exact'])for x in aggregates)==total_kg and sum(D(x['value_eur_exact'])for x in aggregates)==total_eur
old=[x for x in out if x['baseline_status']=='OLD_BASELINE_CN'];new=[x for x in out if x['baseline_status']=='NEW_CN']
assert len(old)==11 and len(new)==29 and sum(D(str(x['volume_kg']))for x in old)==D('30932074') and sum(D(str(x['trade_value_eur']))for x in old)==D('35685420')
save('RECONCILIATION',{'total_kg_exact':str(total_kg),'total_tonnes_exact':str(total_kg/1000),'total_eur_exact':str(total_eur),'partition_residual_kg':'0','partition_residual_eur':'0','old_11_baseline_match':'PASS','old_11_kg':'30932074','old_11_eur':'35685420','new_29_kg':'220083027','new_29_eur':'364752908','display_tonne_tolerance_per_value':'.005','display_component_sum_tolerance_tonnes':'.02','rounding_only':'Exact kg/euro reconciliation is mandatory; 0.02t is max four independently rounded display components, not a source-value correction.','volume':'PASS','value':'PASS'})
species=load(I/'SPECIES_COVERAGE.json');assert len(species)==121
for s in species:
 s['coverage_reporting_bucket']='DIRECT_TRADE_DATA' if s['coverage']in['SPECIES_SPECIFIC','PARTIAL_SPECIES_SCOPE'] else 'GROUP_LEVEL_TRADE_EVIDENCE' if s['coverage']=='GROUP_LEVEL_ONLY' else 'NO_TRADE_EVIDENCE'
 s['direct_scope']='FULL_BOTANICAL_SCOPE' if s['coverage']=='SPECIES_SPECIFIC' else 'LIMITED_CROP_TYPE_OR_INFRASPECIFIC_SCOPE' if s['coverage']=='PARTIAL_SPECIES_SCOPE' else None
 s['species_precision_disclosure']='Direct partial scope is not total species trade; group evidence has no measured constituent value.'
save('SPECIES_COVERAGE',species)
counts=dict(collections.Counter(x['coverage_reporting_bucket']for x in species));detail=dict(collections.Counter(x['coverage']for x in species))
save('SPECIES_COVERAGE_SUMMARY',{'mutually_exclusive':counts,'precision_subcounts':detail,'direct_includes_four_partial_scope_species':True,'species_group_values_allocated':False,'121_kpi_changed':False})
category=[]
for c in load(R/'docs/crop-master-v1/CATEGORY_TAXONOMY_V1.json'):
 rr=[x for x in out if x['allocated_category']==c['id']];kg=sum(D(str(x['volume_kg']))for x in rr);eur=sum(D(str(x['trade_value_eur']))for x in rr)
 candidate_ids=set(v['id']for x in rr for v in x['linked_botanical_species_measured']+x['linked_scope_candidates_only'])
 commercial=set(v for x in rr for v in x['direct_commercial_entity_ids'])
 direct_species=set(v['id']for x in rr if x['audited_granularity']=='SPECIES_SPECIFIC' for v in x['linked_botanical_species_measured'])
 partial_species=set(v['id']for x in rr if x['audited_granularity']=='PARTIAL' for v in x['linked_scope_candidates_only'])
 category.append({'category_id':c['id'],'category_name':c['name'],'volume_tonnes':float(kg/1000)if rr else None,'trade_value_eur':float(eur)if rr else None,'cn_count':len(rr),'cn_codes':[x['cn8']for x in rr],'linked_cn_market_entities':len(rr),'linked_existing_direct_commercial_entities':len(commercial),'linked_existing_scope_candidate_entities':len(candidate_ids),'directly_supported_full_scope_species':len(direct_species),'limited_scope_species':len(partial_species-direct_species),'core_volume_share_percent':round(float(kg/total_kg*100),6)if rr else None,'core_value_share_percent':round(float(eur/total_eur*100),6)if rr else None,'state':'MEASURED_CN_CATEGORY_TOTAL' if rr else 'DATA_GAP','allocation':'No constituent species volumes or counts of actual contributors inferred.'})
save('CATEGORY_ANALYSIS',category)
unallocated=[x for x in out if not x['allocated_category']];ukg=sum(D(str(x['volume_kg']))for x in unallocated);ueur=sum(D(str(x['trade_value_eur']))for x in unallocated)
assert sum(D(str(x['volume_tonnes'] or 0))*1000 for x in category)+ukg==total_kg
assert sum(D(str(x['trade_value_eur'] or 0))for x in category)+ueur==total_eur
save('CATEGORY_RECONCILIATION',{'unallocated_cn_codes':[x['cn8']for x in unallocated],'unallocated_kg':str(ukg),'unallocated_eur':str(ueur),'unallocated_value_share_percent':round(float(ueur/total_eur*100),6),'sum_categories_plus_unallocated':'PASS','category_partition_not_species_partition':True,'12099180_note':'Official vegetable customs usage includes scope candidates whose primary SeedTrade categories also include brassica-seeds. Do not silently move commercial entities or allocate this cross-primary-category code.'})
model={'selected':'MODEL_A','release_gate':'PASS_CORE_ONLY','scope':'40 explicitly seed-for-sowing CN8 codes; June 2026 gross intra-EU exporter dispatches, 27 EU reporters; not total EU seed sector or 121-species measured total.','reason':'All recovered 40 CN descriptions explicitly restrict use to sowing. Group-level botanical breadth does not make this headline commodity trade; safe CN-based labeling avoids species precision claims. No additional broader/ambiguous-use universe is present, so MODEL_B would be artificial.','headline':{'volume_tonnes':251015.10,'value_eur':400438328,'label':'EU seed-for-sowing trade · 40 CN codes','period':'2026-06','description':'Gross internal-EU dispatches; species-specific, crop-type and customs-group evidence. Coverage is customs-defined, not complete seed-market coverage.'},'publication_status':'METHODOLOGY_CANDIDATE_ONLY; EXISTING_UI_NOT_APPROVED_UNTIL_IT_CONSUMES_CORRECTED_ATTRIBUTION_RULES','prior_gate':'FAIL_RETAINED_IN_ORIGINAL_AUDIT','prior_fail_resolved_by':decisions,'blocking_cn_codes':[],'ui_changed':False,'partial_history_not_projected':True,'implementation_followup_required':['Apply direct spelt commercial link without KPI change.','Present CN10019120 as common wheat or meslin group; no common-wheat whole-CN allocation.','Keep sugar/fodder beet and cross-category codes unallocated in category totals.','Display CN-defined headline scope and reference month; do not imply biological species completeness or growth from universe expansion.'],'market_rules':{'precision_values':['SPECIES_SPECIFIC','MARKET_ENTITY_SPECIFIC','GROUP_LEVEL','CATEGORY_LEVEL'],'existing_granularity_preserved':['SPECIES_SPECIFIC','PARTIAL','GROUP_LEVEL'],'unit':'tonnes / EUR','grain':'reporter/partner/period/CN/FLOW','no_addition_of_overlapping_views':True,'species_filter_group_behavior':'Show linked CN evidence with full group label and no allocated species volume.','category_totals':'Disjoint category attribution plus explicit UNALLOCATED bucket; never sum category view with CN or species views.','121_species':'Biological de-duplicated KPI separate from 136 searchable commercial entities.','null_means':'Missing, not zero. Empty classification partitions are arithmetic zero, not filled missing observations.'},'providers':{'COMEXT':'PRIMARY_OFFICIAL_AGGREGATE','GlobalWits':'OWNER_SUPPLIED_LICENSE_REVIEW;0_PUBLIC_AGGREGATE_VALUES;NO_NEW_RESEARCH','Datamyne':'ACCESS_PENDING;SEPARATE_FUTURE_LICENSED_EVIDENCE;NO_FABRICATED_DATA'}}
save('MODEL_RECOMMENDATION',model)
save('SPELT_WHEAT_MODEL',{'biological_species':'Triticum aestivum','commercial_spelt_entity':'spelt','commercial_botanical':'Triticum aestivum subsp. spelta','cn8':'10019110','source_master_cn_status':byid['spelt']['cn']['mapping_status'],'direct_commercial_link_recommended':True,'parent_scope':'PARTIAL_INFRASPECIFIC','group_wheat_meslin_cn':'10019120','group_species_allocation':'NONE','121_species_kpi_changed':False,'new_taxonomy':False,'taxonomic_evidence':byid['spelt']['authority_urls'],'source_original_botanical_names':byid['spelt']['original_source_botanical_names']})
checks={'40_cn_accounted':len(out)==40 and len(set(x['cn8']for x in out))==40,'29_new_accounted':len(new)==29,'11_baseline':len(old)==11,'explicit_sowing':all(x['sowing_use_confirmed']for x in out),'public_safe':all(x['public_safe']for x in out),'classification_partition':sum(x['cn_count']for x in aggregates)==40,'exact_volume_and_value_reconciliation':True,'category_reconciliation':True,'species_accounted':sum(counts.values())==121,'existing_market_entities':len(master)==136,'approved_categories':len(category)==10,'catch_crop_species_preserved':True,'spelt_existing_entity_not_new_species':byid['spelt']['species']=='Triticum aestivum','group_no_species_allocation':all(not x['linked_botanical_species_measured']for x in out if x['audited_granularity']=='GROUP_LEVEL'),'mixed_wheat_group':next(x for x in out if x['cn8']=='10019120')['precision']=='GROUP_LEVEL','beet_categories_unallocated':all(not x['allocated_category']for x in out if x['cn8']in['12091000','12092960']),'provenance':all(x['source_evidence']['classification_sha256'] for x in out),'missing_not_zero':all(x['volume_tonnes']is None for x in category if x['cn_count']==0),'interpolation':True,'source_observations_unchanged':True,'duplicate_grains_recovered_audit_pass':True,'no_new_requests':True,'no_provider_value_mixing':True}
assert all(checks.values())
save('TARGETED_QA',{'checks':checks,'failures':[],'status':'PASS','scope':'Recovered-audit methodology and deterministic aggregation; prior raw-cell audit retained. No new extraction or browser visual QA.','recovered_source_qa':sourceqa,'real_emails':0})
save('SUMMARY',{'starting_head':'dbfd99350479044794837269ed7ef2e7b6c2d4ab','audit_version':'r2','audit_sha256':'a3378ef7db11c4c5fc8f8e2a3be71f4435c437f0be384dfc3c1696c243952a30','classification_counts':dict(collections.Counter(x['classification']for x in out)),'model':'MODEL_A','release_gate':'PASS_CORE_ONLY','headline':model['headline'],'species_coverage':counts,'species_precision':detail,'distinct_seed_species':121,'canonical_market_entities':136,'seed_categories':10,'catch_crop_species':52,'unallocated_category_cn':[x['cn8']for x in unallocated],'no_implementation_changes':True})
inputs=[I/x for x in ['CN_AUDIT_40.json','RELEASE_GATE.json','RECONCILIATION.json','AUDIT_QA.json','SPECIES_COVERAGE.json']]+[R/'docs/crop-master-v1'/x for x in ['CROP_MASTER_V1.json','CATEGORY_TAXONOMY_V1.json']]
save('PROVENANCE_MANIFEST',{'inputs':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in inputs],'source_audit_archive_sha256':'a3378ef7db11c4c5fc8f8e2a3be71f4435c437f0be384dfc3c1696c243952a30','source_evidence':'Preserved 1080 raw COMEXT requests, official CN extract and annual concordances in recovered checkpoint.','methodology':'No network collection; exact Decimal sums from audited CN totals; input evidence unchanged.','public_safe_scope':'Only official CN/COMEXT figures and master taxonomy in public candidate; retained owner workbook remains internal license review.','script_sha256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()})
print(json.dumps(load(O/'SUMMARY.json'),indent=2))
